### ISSUE TITLE
我可以用吗

### ISSUE THREAD

**Issue by terrywangt** [lichongjia/EFI-ASUS-B250M#1]
i7-7700(HD630),ASUS-250M-a,RTX2070
您好，我这个配置可以用吗

**Comment by lichongjia** [comment]
当然可以，不过你的CPU跟我的不同，使用的时候最好删掉我的kext里面的CPUFriend.kext和CPUFriendDataProvider.kext，这个是我专门给i5-7500设置的变频文件

**Comment by lichongjia** [comment]
> i7-7700(HD630),ASUS-250M-a,RTX2070
> 您好，我这个配置可以用吗

当然可以，不过你的CPU跟我的不同，使用的时候最好删掉我的kext里面的CPUFriend.kext和CPUFriendDataProvider.kext，这个是我专门给i5-7500设置的变频文件

**Comment by lichongjia** [comment]
> i7-7700(HD630),ASUS-250M-a,RTX2070
> 您好，我这个配置可以用吗

当然可以，不过你的CPU跟我的不同，使用的时候最好删掉我的kext里面的CPUFriend.kext和CPUFriendDataProvider.kext，这个是我专门给i5-7500设置的变频文件，另外你的显卡并不支持10.14及以上，这些都是你需要注意的。

**Comment by terrywangt** [comment]
> > i7-7700（HD630），ASUS-250M-a，RTX2070 
> > 您好，我这个配置可以用吗
> 
> 当然可以，不过你的CPU跟我的不同，使用的时候最好删除掉我的kext里面的CPUFriend.kext和CPUFriendDataProvider.kext，这个是我专门给i5-7500设置的转换文件，另外你的硬盘并不支持10.14及以上，这些都是你需要注意的。

_刚刚试了下，我的配置进不了安装界面，启动安装失败了😭

**Comment by lichongjia** [comment]
有事请关注公众号，看提示。

**Comment by lichongjia** [comment]
> > > i7-7700（HD630），ASUS-250M-a，RTX2070
> > > 您好，我这个配置可以用吗
> > 
> > 
> > 当然可以，不过你的CPU跟我的不同，使用的时候最好删除掉我的kext里面的CPUFriend.kext和CPUFriendDataProvider.kext，这个是我专门给i5-7500设置的转换文件，另外你的硬盘并不支持10.14及以上，这些都是你需要注意的。
> 
> _刚刚试了下，我的配置进不了安装界面，启动安装失败了

有事请关注公众号，看提示。
