### ISSUE TITLE
敢问大佬用的是哪版的os？

### ISSUE THREAD

**Issue by a5234338** [lichongjia/EFI-ASUS-B250M#2]
我技嘉【b250-d3h主板】【7500cpu】【1050Ti显卡】，配置相近。目前用的是13.6的系统（无奈的N卡），替换你这个EFI无法引导启动。想请大佬指点一下，可能是config哪里要改改还是什么问题呢？

**Comment by lichongjia** [comment]
> 我技嘉【b250-d3h主板】【7500cpu】【1050Ti显卡】，配置相近。目前用的是13.6的系统（无奈的N卡），替换你这个EFI无法引导启动。想请大佬指点一下，可能是config哪里要改改还是什么问题呢？

N卡也是可以的，我以前刚好就有用1050Ti测试过。不过配置文件(加启动参数)要更改下，另外你的主板跟我的不同，虽然相似，但是DSDT肯定不同，所以某些改名可能并不适合你的主板，你应该看你自己DSDT下该设备具体名称来决定是否需要更改。

**Comment by lichongjia** [comment]
High Sierra，Mojave，Catalina我都有装，但最终选择了Mojave，个人觉得Mojave比较稳定完善，而且10.15上新增的功能并不适合我，建议用于生产力还是Mojave好，只是你的N卡只能到10.13.6，想要用新系统里只能换显卡，或禁用独显只用核显。也够用了！

**Comment by lichongjia** [comment]
- HighSierra,Mojave,Catalina我都有装，但最终选择了Mojave
- 个人觉得Mojave比较成熟稳定，而且10.15上新增的功能和特性并不适合我。
- 建议用于生产力还是Mojave好
- 只是你的N卡驱动只能到10.13.6，要想用新系统，你有两种方式选择：
  1. 换显卡，换成A卡
  2. 或禁用独显只用核显。也够用了！

**Comment by a5234338** [comment]
- 烦人，又搞了2天了，还搞砸了。
 - 系统重新装了下（13.6），还是之前的EFI。但是web driver的pkg文件死活打不开，提示什么版本问题，各种方法都找了个遍。
 - 用你的Clover改了改貌似是可以引导到系统的（OC失败，查了config你开了nvram，你主板支持吗？还开了N卡，记得是31），但是体现出来的完成度不高。不过想想也是，这是你针对自己一套硬件做的优化。通用性高的EFI比较粗糙，针对性强的EFI文件局限性也大，结果就是适配性都不尽如人意。就没找到像你一样完成度比较高的大佬，同型号的主板。。
 - DSDT应该不能照搬你的吧，就改名就行？

**Comment by a5234338** [comment]
用核显引导显卡也没搞定

- 闪屏（鼠标动一下就闪，吐血）
- 4k显示器没hidpi（不是说4k显示器hidpi自动开么）
- 另外核显貌似睡眠无解

**Comment by lichongjia** [comment]
> 用核显引导显卡也没搞定
> 
> * 闪屏（鼠标动一下就闪，吐血）
> * 4k显示器没hidpi（不是说4k显示器hidpi自动开么）
> * 另外核显貌似睡眠无解

用核显的话，建议通过DSDT禁用N卡，然后换SMBios为iMac18,1。你这个配置很好弄，完全可以设置得很完美！

**Comment by a5234338** [comment]
邮件写的有点乱，见谅~
现在在下小兵的镜像，明天计划重做系统试试

**Comment by lichongjia** [comment]
赶紧的，赶紧的，加我微信(chongjialee)，趁我这会儿有空。邮件和github都不及时。


发自我的iPhone

------------------ 原始邮件 ------------------
发件人: a5234338 <notifications@github.com&gt;
发送时间: 2020年1月28日 22:55
收件人: lichongjia/EFI-ASUS-B250M <EFI-ASUS-B250M@noreply.github.com&gt;
抄送: 见风致 <lichongjia@vip.qq.com&gt;, Comment <comment@noreply.github.com&gt;
主题: 回复：[lichongjia/EFI-ASUS-B250M] 敢问大佬用的是哪版的os？ (#2)




邮件写的有点乱，见谅~
 现在在下小兵的镜像，明天计划重做系统试试

**Comment by a5234338** [comment]
来晚了~~~

**Comment by a5234338** [comment]
要疯！！小兵的镜像，先后做了2个U盘，安装都是说损坏。来校验MD5，没异常。。。。。。




------------------&nbsp;原始邮件&nbsp;------------------
发件人:&nbsp;"见风致"<notifications@github.com&gt;;
发送时间:&nbsp;2020年1月28日(星期二) 晚上11:38
收件人:&nbsp;"lichongjia/EFI-ASUS-B250M"<EFI-ASUS-B250M@noreply.github.com&gt;;
抄送:&nbsp;"狒狒"<zhangziheng2007@qq.com&gt;;"Author"<author@noreply.github.com&gt;;
主题:&nbsp;Re: [lichongjia/EFI-ASUS-B250M] 敢问大佬用的是哪版的os？ (#2)



赶紧的，赶紧的，加我微信(chongjialee)，趁我这会儿有空。邮件和github都不及时。 
 
 
 发自我的iPhone 
 
 ------------------ 原始邮件 ------------------ 
 发件人: a5234338 <notifications@github.com&amp;gt; 
 发送时间: 2020年1月28日 22:55 
 收件人: lichongjia/EFI-ASUS-B250M <EFI-ASUS-B250M@noreply.github.com&amp;gt; 
 抄送: 见风致 <lichongjia@vip.qq.com&amp;gt;, Comment <comment@noreply.github.com&amp;gt; 
 主题: 回复：[lichongjia/EFI-ASUS-B250M] 敢问大佬用的是哪版的os？ (#2) 
 
 
 
 
 邮件写的有点乱，见谅~ 
  现在在下小兵的镜像，明天计划重做系统试试
