### ISSUE TITLE
求助大佬，用核显HD630第一次载入无法完成是什么情况

### ISSUE THREAD

**Issue by shad0whz** [lichongjia/EFI-ASUS-B250M#4]
显卡是R7 240，之前用大佬的EFI装 黑果小兵的macOS Catalina 10.15.3 19D76，除了显卡没用其他一切正常，显存显示5M，后来我把显卡拆了但是系统无法启动了，我想着重新装一遍，但是卡在进入clover选择安装之后第一次读条的地方，条没读完就自动重启，然后又进入clover。

求大佬协助，新手第一次装，很多地方不是很懂。

**Comment by shad0whz** [comment]
主板：华硕B250M-KYLIN
CPU :  i5-7500

**Comment by lichongjia** [comment]
> 显卡是R7 240，之前用大佬的EFI装 黑果小兵的macOS Catalina 10.15.3 19D76，除了显卡没用其他一切正常，显存显示5M，后来我把显卡拆了但是系统无法启动了，我想着重新装一遍，但是卡在进入clover选择安装之后第一次读条的地方，条没读完就自动重启，然后又进入clover。
> 
> 求大佬协助，新手第一次装，很多地方不是很懂。

你这显卡如果不是免驱卡，可能需要仿冒驱动，只能自己去尝试，至于拆显卡无法启动，那是正常现象，因为核显我用的是无头模式，仅作加速用，所以它不可能有输出。

**Comment by shad0whz** [comment]
大佬，怎么设置clover才能把无头模式去掉，这个显卡也是很垃圾的，不如直接用核显，我搜了半天把GFX0 to IGPU禁用，然后注入核显的ig-platform-id，但是好像更没用了，哎

**Comment by lichongjia** [comment]
> 大佬，怎么设置clover才能把无头模式去掉，这个显卡也是很垃圾的，不如直接用核显，我搜了半天把GFX0 to IGPU禁用，然后注入核显的ig-platform-id，但是好像更没用了，哎

如果确信自己搞不定的话，就通过主页的公众号来找我吧！

**Comment by a5234338** [comment]
> 大佬，怎么设置clover才能把无头模式去掉，这个显卡也是很垃圾的，不如直接用核显，我搜了半天把GFX0 to IGPU禁用，然后注入核显的ig-platform-id，但是好像更没用了，哎

https://blog.zuiyu1818.cn/posts/Hac_Intel_Graphics.html可以参考这个，很详细

**Comment by a5234338** [comment]
> > 大佬，怎么设置clover才能把无头模式去掉，这个显卡也是很垃圾的，不如直接用核显，我搜了半天把GFX0 to IGPU禁用，然后注入核显的ig-platform-id，但是好像更没用了，哎
> 
> [https://blog.zuiyu1818.cn/posts/Hac_Intel_Graphics.html可以参考这个，很详细](https://blog.zuiyu1818.cn/posts/Hac_Intel_Graphics.html%E5%8F%AF%E4%BB%A5%E5%8F%82%E8%80%83%E8%BF%99%E4%B8%AA%EF%BC%8C%E5%BE%88%E8%AF%A6%E7%BB%86)

[再发一遍，应该不回粘在一起了](https://blog.zuiyu1818.cn/posts/Hac_Intel_Graphics.html)

**Comment by a5234338** [comment]
> 大佬，怎么设置clover才能把无头模式去掉，这个显卡也是很垃圾的，不如直接用核显，我搜了半天把GFX0 to IGPU禁用，然后注入核显的ig-platform-id，但是好像更没用了，哎

`https://blog.zuiyu1818.cn/posts/Hac_Intel_Graphics.html`可以参考这个，很详细

**Comment by shad0whz** [comment]
> > 大佬，怎么设置clover才能把无头模式去掉，这个插件也是很垃圾的，不如直接用核显，我搜了半天把GFX0到IGPU，然后注入核显的ig-platform-id，但是好像更容易没用了，哎
> 
> `https://blog.zuiyu1818.cn/posts/Hac_Intel_Graphics.html`可以参考这个，很详细

感谢感谢，我在大佬的帮助下已经弄好了

**Comment by marianopela** [comment]
Hi! @shad0whz I'm having the same problem you had with patching iGPU (I don't have a dGPU). Could you please share the working patch you're using? Thanks!

**Comment by lichongjia** [comment]
> Hi! @shad0whz I'm having the same problem you had with patching iGPU (I don't have a dGPU). Could you please share the working patch you're using? Thanks!

if you used iGPU to drive a display, in my opinion the easiest way is to change the AAPL,ig-platform-id to 00001259 and 03001259 is a Headless PlatformID which is only used for computing tasks and doesn't drive a display.
